# Generated by Django 5.2.9 on 2026-08-16 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            (
                                "crop_species_proposal_accepted",
                                "Crop species proposal accepted",
                            ),
                            (
                                "crop_species_proposal_rejected",
                                "Crop species proposal rejected",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="English fallback text for admin/API consumers; the app UI localizes notification_type + context instead."
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Placeholder values for the localized message, e.g. {"name": "Pumpkin"}.',
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public_culture", "Public culture"),
                            ("crop_species", "Crop species"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    )
                ],
            },
        ),
    ]
