# Generated by Django 5.2.9 on 2026-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('crop_species_proposal_accepted', 'Crop species proposal accepted'), ('crop_species_proposal_rejected', 'Crop species proposal rejected'), ('crop_species_proposal_submitted', 'Crop species proposal submitted'), ('moderator_request_submitted', 'Moderator request submitted')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('public_culture', 'Public culture'), ('crop_species', 'Crop species'), ('public_library_moderation', 'Public library moderation queue')], max_length=32),
        ),
    ]
