# Generated by Django 5.2.9 on 2026-08-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('crop_species_proposal_accepted', 'Crop species proposal accepted'), ('crop_species_proposal_rejected', 'Crop species proposal rejected'), ('crop_species_proposal_submitted', 'Crop species proposal submitted'), ('moderator_request_submitted', 'Moderator request submitted'), ('public_culture_removed', 'Public culture removed')], max_length=64),
        ),
    ]
