"""Central seed data for official crop-library species."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CropSpeciesSeedEntry:
    """Language-independent species entry prepared for later translations."""

    key: str
    translations: dict[str, str]


CROP_SPECIES_SEED_DATA: tuple[CropSpeciesSeedEntry, ...] = (
    CropSpeciesSeedEntry(key='amaranth', translations={'de': 'Amaranth', 'en': 'Amaranth'}),
    CropSpeciesSeedEntry(key='apple', translations={'de': 'Apfel', 'en': 'Apple'}),
    CropSpeciesSeedEntry(key='apricot', translations={'de': 'Marille', 'en': 'Apricot'}),
    CropSpeciesSeedEntry(key='artichoke', translations={'de': 'Artischocke', 'en': 'Artichoke'}),
    CropSpeciesSeedEntry(key='asparagus', translations={'de': 'Spargel', 'en': 'Asparagus'}),
    CropSpeciesSeedEntry(key='aubergine', translations={'de': 'Aubergine', 'en': 'Eggplant'}),
    CropSpeciesSeedEntry(key='barley', translations={'de': 'Gerste', 'en': 'Barley'}),
    CropSpeciesSeedEntry(key='basil', translations={'de': 'Basilikum', 'en': 'Basil'}),
    CropSpeciesSeedEntry(key='beetroot', translations={'de': 'Rote Rübe', 'en': 'Beetroot'}),
    CropSpeciesSeedEntry(key='black_salsify', translations={'de': 'Schwarzwurzel', 'en': 'Black salsify'}),
    CropSpeciesSeedEntry(key='blackcurrant', translations={'de': 'Schwarze Ribisel', 'en': 'Blackcurrant'}),
    CropSpeciesSeedEntry(key='blackberry', translations={'de': 'Brombeere', 'en': 'Blackberry'}),
    CropSpeciesSeedEntry(key='blueberry', translations={'de': 'Heidelbeere', 'en': 'Blueberry'}),
    CropSpeciesSeedEntry(key='borage', translations={'de': 'Borretsch', 'en': 'Borage'}),
    CropSpeciesSeedEntry(key='broad_bean', translations={'de': 'Ackerbohne', 'en': 'Broad bean'}),
    CropSpeciesSeedEntry(key='broccoli', translations={'de': 'Brokkoli', 'en': 'Broccoli'}),
    CropSpeciesSeedEntry(key='brussels_sprout', translations={'de': 'Rosenkohl', 'en': 'Brussels sprout'}),
    CropSpeciesSeedEntry(key='buckwheat', translations={'de': 'Buchweizen', 'en': 'Buckwheat'}),
    CropSpeciesSeedEntry(key='bush_bean', translations={'de': 'Buschbohne', 'en': 'Bush bean'}),
    CropSpeciesSeedEntry(key='cabbage', translations={'de': 'Weißkraut', 'en': 'White cabbage'}),
    CropSpeciesSeedEntry(key='camelina', translations={'de': 'Leindotter', 'en': 'Camelina'}),
    CropSpeciesSeedEntry(key='canola', translations={'de': 'Raps', 'en': 'Canola'}),
    CropSpeciesSeedEntry(key='caraway', translations={'de': 'Kümmel', 'en': 'Caraway'}),
    CropSpeciesSeedEntry(key='cardoon', translations={'de': 'Kardy', 'en': 'Cardoon'}),
    CropSpeciesSeedEntry(key='carrot', translations={'de': 'Karotte', 'en': 'Carrot'}),
    CropSpeciesSeedEntry(key='cauliflower', translations={'de': 'Karfiol', 'en': 'Cauliflower'}),
    CropSpeciesSeedEntry(key='celeriac', translations={'de': 'Knollensellerie', 'en': 'Celeriac'}),
    CropSpeciesSeedEntry(key='celery', translations={'de': 'Stangensellerie', 'en': 'Celery'}),
    CropSpeciesSeedEntry(key='chamomile', translations={'de': 'Kamille', 'en': 'Chamomile'}),
    CropSpeciesSeedEntry(key='chard', translations={'de': 'Mangold', 'en': 'Chard'}),
    CropSpeciesSeedEntry(key='cherry', translations={'de': 'Kirsche', 'en': 'Cherry'}),
    CropSpeciesSeedEntry(key='chestnut', translations={'de': 'Edelkastanie', 'en': 'Chestnut'}),
    CropSpeciesSeedEntry(key='chervil', translations={'de': 'Kerbel', 'en': 'Chervil'}),
    CropSpeciesSeedEntry(key='chickpea', translations={'de': 'Kichererbse', 'en': 'Chickpea'}),
    CropSpeciesSeedEntry(key='chinese_cabbage', translations={'de': 'Chinakohl', 'en': 'Chinese cabbage'}),
    CropSpeciesSeedEntry(key='chicory', translations={'de': 'Chicorée', 'en': 'Chicory'}),
    CropSpeciesSeedEntry(key='chili', translations={'de': 'Chili', 'en': 'Chili pepper'}),
    CropSpeciesSeedEntry(key='chives', translations={'de': 'Schnittlauch', 'en': 'Chives'}),
    CropSpeciesSeedEntry(key='common_vetch', translations={'de': 'Saatwicke', 'en': 'Common vetch'}),
    CropSpeciesSeedEntry(key='coriander', translations={'de': 'Koriander', 'en': 'Coriander'}),
    CropSpeciesSeedEntry(key='corn_salad', translations={'de': 'Feldsalat', 'en': 'Corn salad'}),
    CropSpeciesSeedEntry(key='cress', translations={'de': 'Kresse', 'en': 'Cress'}),
    CropSpeciesSeedEntry(key='cucumber', translations={'de': 'Gurke', 'en': 'Cucumber'}),
    CropSpeciesSeedEntry(key='currant', translations={'de': 'Ribisel', 'en': 'Currant'}),
    CropSpeciesSeedEntry(key='daikon', translations={'de': 'Rettich', 'en': 'Daikon radish'}),
    CropSpeciesSeedEntry(key='dill', translations={'de': 'Dill', 'en': 'Dill'}),
    CropSpeciesSeedEntry(key='durum_wheat', translations={'de': 'Hartweizen', 'en': 'Durum wheat'}),
    CropSpeciesSeedEntry(key='einkorn', translations={'de': 'Einkorn', 'en': 'Einkorn'}),
    CropSpeciesSeedEntry(key='elderberry', translations={'de': 'Holunder', 'en': 'Elderberry'}),
    CropSpeciesSeedEntry(key='emmer', translations={'de': 'Emmer', 'en': 'Emmer'}),
    CropSpeciesSeedEntry(key='endive', translations={'de': 'Endivie', 'en': 'Endive'}),
    CropSpeciesSeedEntry(key='fennel_bulb', translations={'de': 'Knollenfenchel', 'en': 'Florence fennel'}),
    CropSpeciesSeedEntry(key='fennel', translations={'de': 'Fenchel', 'en': 'Fennel'}),
    CropSpeciesSeedEntry(key='field_pea', translations={'de': 'Futtererbse', 'en': 'Field pea'}),
    CropSpeciesSeedEntry(key='flax', translations={'de': 'Lein', 'en': 'Flax'}),
    CropSpeciesSeedEntry(key='fodder_beet', translations={'de': 'Futterrübe', 'en': 'Fodder beet'}),
    CropSpeciesSeedEntry(key='french_bean', translations={'de': 'Grüne Bohne', 'en': 'French bean'}),
    CropSpeciesSeedEntry(key='garlic', translations={'de': 'Knoblauch', 'en': 'Garlic'}),
    CropSpeciesSeedEntry(key='gooseberry', translations={'de': 'Stachelbeere', 'en': 'Gooseberry'}),
    CropSpeciesSeedEntry(key='grape', translations={'de': 'Weintraube', 'en': 'Grape'}),
    CropSpeciesSeedEntry(key='green_manure', translations={'de': 'Gründüngung', 'en': 'Green manure'}),
    CropSpeciesSeedEntry(key='hazelnut', translations={'de': 'Haselnuss', 'en': 'Hazelnut'}),
    CropSpeciesSeedEntry(key='hemp', translations={'de': 'Hanf', 'en': 'Hemp'}),
    CropSpeciesSeedEntry(key='hop', translations={'de': 'Hopfen', 'en': 'Hop'}),
    CropSpeciesSeedEntry(key='horseradish', translations={'de': 'Kren', 'en': 'Horseradish'}),
    CropSpeciesSeedEntry(key='iceberg_lettuce', translations={'de': 'Eisbergsalat', 'en': 'Iceberg lettuce'}),
    CropSpeciesSeedEntry(key='jerusalem_artichoke', translations={'de': 'Topinambur', 'en': 'Jerusalem artichoke'}),
    CropSpeciesSeedEntry(key='kale', translations={'de': 'Grünkohl', 'en': 'Kale'}),
    CropSpeciesSeedEntry(key='kidney_bean', translations={'de': 'Kidneybohne', 'en': 'Kidney bean'}),
    CropSpeciesSeedEntry(key='kiwi', translations={'de': 'Kiwi', 'en': 'Kiwi'}),
    CropSpeciesSeedEntry(key='kohlrabi', translations={'de': 'Kohlrabi', 'en': 'Kohlrabi'}),
    CropSpeciesSeedEntry(key='lavender', translations={'de': 'Lavendel', 'en': 'Lavender'}),
    CropSpeciesSeedEntry(key='leek', translations={'de': 'Lauch', 'en': 'Leek'}),
    CropSpeciesSeedEntry(key='lemon_balm', translations={'de': 'Zitronenmelisse', 'en': 'Lemon balm'}),
    CropSpeciesSeedEntry(key='lentil', translations={'de': 'Linse', 'en': 'Lentil'}),
    CropSpeciesSeedEntry(key='lettuce', translations={'de': 'Salat', 'en': 'Lettuce'}),
    CropSpeciesSeedEntry(key='lovage', translations={'de': 'Liebstöckel', 'en': 'Lovage'}),
    CropSpeciesSeedEntry(key='lupin', translations={'de': 'Lupine', 'en': 'Lupin'}),
    CropSpeciesSeedEntry(key='maize', translations={'de': 'Mais', 'en': 'Maize'}),
    CropSpeciesSeedEntry(key='marjoram', translations={'de': 'Majoran', 'en': 'Marjoram'}),
    CropSpeciesSeedEntry(key='medlar', translations={'de': 'Mispel', 'en': 'Medlar'}),
    CropSpeciesSeedEntry(key='melon', translations={'de': 'Melone', 'en': 'Melon'}),
    CropSpeciesSeedEntry(key='mint', translations={'de': 'Minze', 'en': 'Mint'}),
    CropSpeciesSeedEntry(key='mung_bean', translations={'de': 'Mungbohne', 'en': 'Mung bean'}),
    CropSpeciesSeedEntry(key='mustard', translations={'de': 'Senf', 'en': 'Mustard'}),
    CropSpeciesSeedEntry(key='nectarine', translations={'de': 'Nektarine', 'en': 'Nectarine'}),
    CropSpeciesSeedEntry(key='oat', translations={'de': 'Hafer', 'en': 'Oat'}),
    CropSpeciesSeedEntry(key='okra', translations={'de': 'Okra', 'en': 'Okra'}),
    CropSpeciesSeedEntry(key='onion', translations={'de': 'Zwiebel', 'en': 'Onion'}),
    CropSpeciesSeedEntry(key='oregano', translations={'de': 'Oregano', 'en': 'Oregano'}),
    CropSpeciesSeedEntry(key='pak_choi', translations={'de': 'Pak Choi', 'en': 'Pak choi'}),
    CropSpeciesSeedEntry(key='parsley_root', translations={'de': 'Wurzelpetersilie', 'en': 'Parsley root'}),
    CropSpeciesSeedEntry(key='parsley', translations={'de': 'Petersilie', 'en': 'Parsley'}),
    CropSpeciesSeedEntry(key='parsnip', translations={'de': 'Pastinake', 'en': 'Parsnip'}),
    CropSpeciesSeedEntry(key='pattypan_squash', translations={'de': 'Patisson', 'en': 'Pattypan squash'}),
    CropSpeciesSeedEntry(key='peach', translations={'de': 'Pfirsich', 'en': 'Peach'}),
    CropSpeciesSeedEntry(key='peanut', translations={'de': 'Erdnuss', 'en': 'Peanut'}),
    CropSpeciesSeedEntry(key='pea', translations={'de': 'Erbse', 'en': 'Pea'}),
    CropSpeciesSeedEntry(key='pear', translations={'de': 'Birne', 'en': 'Pear'}),
    CropSpeciesSeedEntry(key='pepper', translations={'de': 'Paprika', 'en': 'Sweet pepper'}),
    CropSpeciesSeedEntry(key='physalis', translations={'de': 'Physalis', 'en': 'Physalis'}),
    CropSpeciesSeedEntry(key='pole_bean', translations={'de': 'Stangenbohne', 'en': 'Pole bean'}),
    CropSpeciesSeedEntry(key='plum', translations={'de': 'Zwetschke', 'en': 'Plum'}),
    CropSpeciesSeedEntry(key='potato', translations={'de': 'Kartoffel', 'en': 'Potato'}),
    CropSpeciesSeedEntry(key='pumpkin', translations={'de': 'Kürbis', 'en': 'Pumpkin'}),
    CropSpeciesSeedEntry(key='quince', translations={'de': 'Quitte', 'en': 'Quince'}),
    CropSpeciesSeedEntry(key='radicchio', translations={'de': 'Radicchio', 'en': 'Radicchio'}),
    CropSpeciesSeedEntry(key='radish', translations={'de': 'Radieschen', 'en': 'Radish'}),
    CropSpeciesSeedEntry(key='ramson', translations={'de': 'Bärlauch', 'en': 'Ramson'}),
    CropSpeciesSeedEntry(key='raspberry', translations={'de': 'Himbeere', 'en': 'Raspberry'}),
    CropSpeciesSeedEntry(key='red_cabbage', translations={'de': 'Rotkraut', 'en': 'Red cabbage'}),
    CropSpeciesSeedEntry(key='rhubarb', translations={'de': 'Rhabarber', 'en': 'Rhubarb'}),
    CropSpeciesSeedEntry(key='romaine_lettuce', translations={'de': 'Römersalat', 'en': 'Romaine lettuce'}),
    CropSpeciesSeedEntry(key='rosemary', translations={'de': 'Rosmarin', 'en': 'Rosemary'}),
    CropSpeciesSeedEntry(key='rocket', translations={'de': 'Rucola', 'en': 'Rocket'}),
    CropSpeciesSeedEntry(key='runner_bean', translations={'de': 'Feuerbohne', 'en': 'Runner bean'}),
    CropSpeciesSeedEntry(key='rye', translations={'de': 'Roggen', 'en': 'Rye'}),
    CropSpeciesSeedEntry(key='sage', translations={'de': 'Salbei', 'en': 'Sage'}),
    CropSpeciesSeedEntry(key='savory', translations={'de': 'Bohnenkraut', 'en': 'Savory'}),
    CropSpeciesSeedEntry(key='savoy_cabbage', translations={'de': 'Wirsing', 'en': 'Savoy cabbage'}),
    CropSpeciesSeedEntry(key='sea_buckthorn', translations={'de': 'Sanddorn', 'en': 'Sea buckthorn'}),
    CropSpeciesSeedEntry(key='shallot', translations={'de': 'Schalotte', 'en': 'Shallot'}),
    CropSpeciesSeedEntry(key='sorghum', translations={'de': 'Sorghum', 'en': 'Sorghum'}),
    CropSpeciesSeedEntry(key='sorrel', translations={'de': 'Sauerampfer', 'en': 'Sorrel'}),
    CropSpeciesSeedEntry(key='soybean', translations={'de': 'Sojabohne', 'en': 'Soybean'}),
    CropSpeciesSeedEntry(key='spinach', translations={'de': 'Spinat', 'en': 'Spinach'}),
    CropSpeciesSeedEntry(key='spelt', translations={'de': 'Dinkel', 'en': 'Spelt'}),
    CropSpeciesSeedEntry(key='pointed_cabbage', translations={'de': 'Spitzkraut', 'en': 'Pointed cabbage'}),
    CropSpeciesSeedEntry(key='spring_onion', translations={'de': 'Frühlingszwiebel', 'en': 'Spring onion'}),
    CropSpeciesSeedEntry(key='strawberry', translations={'de': 'Erdbeere', 'en': 'Strawberry'}),
    CropSpeciesSeedEntry(key='sugar_beet', translations={'de': 'Zuckerrübe', 'en': 'Sugar beet'}),
    CropSpeciesSeedEntry(key='sunflower', translations={'de': 'Sonnenblume', 'en': 'Sunflower'}),
    CropSpeciesSeedEntry(key='summer_squash', translations={'de': 'Zucchini', 'en': 'Zucchini'}),
    CropSpeciesSeedEntry(key='sweet_potato', translations={'de': 'Süßkartoffel', 'en': 'Sweet potato'}),
    CropSpeciesSeedEntry(key='sweetcorn', translations={'de': 'Zuckermais', 'en': 'Sweetcorn'}),
    CropSpeciesSeedEntry(key='tarragon', translations={'de': 'Estragon', 'en': 'Tarragon'}),
    CropSpeciesSeedEntry(key='thyme', translations={'de': 'Thymian', 'en': 'Thyme'}),
    CropSpeciesSeedEntry(key='tomato', translations={'de': 'Tomate', 'en': 'Tomato'}),
    CropSpeciesSeedEntry(key='triticale', translations={'de': 'Triticale', 'en': 'Triticale'}),
    CropSpeciesSeedEntry(key='turnip', translations={'de': 'Speiserübe', 'en': 'Turnip'}),
    CropSpeciesSeedEntry(key='walnut', translations={'de': 'Walnuss', 'en': 'Walnut'}),
    CropSpeciesSeedEntry(key='watermelon', translations={'de': 'Wassermelone', 'en': 'Watermelon'}),
    CropSpeciesSeedEntry(key='wheat', translations={'de': 'Weizen', 'en': 'Wheat'}),
)


def get_crop_species_seed_name(entry: CropSpeciesSeedEntry, language_code: str = 'de') -> str:
    """Return the best display name currently supported by the species model."""
    return entry.translations.get(language_code) or entry.translations['de']
