# Generated by Django 5.2.9 on 2026-07-27 06:23

import django.core.serializers.json
import django.db.models.deletion
import json
from django.conf import settings
from django.db import migrations, models


PUBLIC_CULTURE_REVISION_SNAPSHOT_FIELDS = [
    'name',
    'variety',
    'notes',
    'seed_supplier',
    'supplier_name',
    'crop_family',
    'nutrient_demand',
    'cultivation_types',
    'cultivation_type',
    'growth_duration_days',
    'harvest_duration_days',
    'propagation_duration_days',
    'harvest_method',
    'expected_yield',
    'allow_deviation_delivery_weeks',
    'distance_within_row_m',
    'row_spacing_m',
    'sowing_depth_m',
    'seed_rate_value',
    'seed_rate_unit',
    'seed_rate_by_cultivation',
    'sowing_calculation_safety_percent',
    'thousand_kernel_weight_g',
    'seeding_requirement',
    'seeding_requirement_type',
    'display_color',
    'seed_packages',
]


def json_safe(value):
    return json.loads(json.dumps(value, cls=django.core.serializers.json.DjangoJSONEncoder))


def backfill_public_culture_revisions(apps, schema_editor):
    PublicCulture = apps.get_model('farm', 'PublicCulture')
    PublicCultureRevision = apps.get_model('farm', 'PublicCultureRevision')
    rows = []
    for public_culture in PublicCulture.objects.all().iterator():
        snapshot = {
            field: json_safe(getattr(public_culture, field))
            for field in PUBLIC_CULTURE_REVISION_SNAPSHOT_FIELDS
        }
        snapshot['crop_species'] = public_culture.crop_species_id
        snapshot['original_language_code'] = public_culture.original_language_code
        rows.append(PublicCultureRevision(
            public_culture_id=public_culture.id,
            version=max(public_culture.version or 1, 1),
            action='created',
            snapshot=snapshot,
            changed_fields=[],
            created_by_id=public_culture.created_by_id,
            created_at=public_culture.published_at or public_culture.created_at,
        ))
        if len(rows) >= 500:
            PublicCultureRevision.objects.bulk_create(rows, ignore_conflicts=True)
            rows = []
    if rows:
        PublicCultureRevision.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0079_publicculturechangeproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCultureRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('restored', 'Restored')], default='updated', max_length=20)),
                ('snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_fields', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('restored_from_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_culture_revisions', to=settings.AUTH_USER_MODEL)),
                ('public_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='farm.publicculture')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('public_culture', 'version'), name='unique_public_culture_revision_version')],
            },
        ),
        migrations.RunPython(backfill_public_culture_revisions, noop_reverse),
    ]
