# Generated by Django 5.2.9 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0081_structured_public_culture_discussions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicCultureTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="farm.publicculture",
                    ),
                ),
            ],
            options={
                "ordering": ["language_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("public_culture", "language_code"),
                        name="unique_public_culture_translation_per_language",
                    )
                ],
            },
        ),
    ]
