# Generated by Django 5.2.9 on 2026-07-29 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0083_backfill_public_culture_translations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureImportDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_label", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending confirmation"),
                            ("applied", "Applied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("checksum", models.CharField(editable=False, max_length=64)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("has_errors", models.BooleanField(default=False)),
                ("has_warnings", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_import_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_import_drafts",
                        to="farm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label chosen by the owner",
                        max_length=120,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("read", "Read only"), ("write", "Read and write")],
                        default="read",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        editable=False,
                        help_text="Non-secret leading characters used to identify the token in listings",
                        max_length=16,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="farm.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "project"],
                        name="farm_projec_user_id_9f8cc7_idx",
                    )
                ],
            },
        ),
    ]
