# Generated by Django 5.2.9 on 2026-08-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0084_remove_public_culture_supplier_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="rejected_public_version",
            field=models.IntegerField(
                blank=True,
                help_text="Public-library version the user explicitly declined to take over. Only silences the update notice for exactly that version; a newer public version surfaces the notice again.",
                null=True,
            ),
        ),
    ]
