# Generated by Django 5.2.9 on 2026-08-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0087_projectapitoken_delete_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicculture',
            name='removal_reason',
            field=models.CharField(blank=True, choices=[('accidental_publication', 'Accidental publication'), ('test_data', 'Test data'), ('duplicate', 'Duplicate'), ('wrong_mapping', 'Wrong mapping'), ('unlawful_content', 'Unlawful content'), ('species_rejected', 'Crop species rejected'), ('other', 'Other')], max_length=50),
        ),
    ]
