# Generated by Django 5.2.9 on 2026-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0088_alter_publicculture_removal_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='rotation_break_years',
            field=models.IntegerField(blank=True, help_text='Recommended crop rotation break in years before growing this crop family again', null=True),
        ),
    ]
