# Generated by Codex on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0089_add_culture_rotation_break_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(
                choices=[
                    ('germany', 'Germany'),
                    ('austria', 'Austria'),
                    ('switzerland', 'Switzerland'),
                ],
                default='germany',
                max_length=20,
            ),
        ),
    ]
