# Generated by Codex on 2026-08-21

from django.db import migrations, models


def _normalize_text(value: str | None) -> str | None:
    if not value:
        return None
    normalized = ' '.join(str(value).split()).casefold()
    return normalized or None


def assert_no_duplicate_general_culture_names(apps, _schema_editor) -> None:
    Culture = apps.get_model('farm', 'Culture')
    Project = apps.get_model('farm', 'Project')

    duplicates: dict[tuple[int, str], list[int]] = {}
    rows = (
        Culture.objects
        .filter(deleted_at__isnull=True)
        .filter(models.Q(variety_normalized__isnull=True) | models.Q(variety_normalized=''))
        .values('id', 'project_id', 'name', 'name_normalized')
    )
    for row in rows.iterator():
        normalized_name = row['name_normalized'] or _normalize_text(row['name'])
        if not normalized_name:
            continue
        duplicates.setdefault((row['project_id'], normalized_name), []).append(row['id'])

    conflicts = [
        (project_id, normalized_name, ids)
        for (project_id, normalized_name), ids in duplicates.items()
        if len(ids) > 1
    ]
    if not conflicts:
        return

    project_names = {
        project.id: project.name
        for project in Project.objects.filter(id__in={project_id for project_id, _, _ in conflicts})
    }
    details = '; '.join(
        f'{project_names.get(project_id, project_id)} / {normalized_name}: ids {", ".join(map(str, ids))}'
        for project_id, normalized_name, ids in conflicts[:20]
    )
    remaining = len(conflicts) - 20
    suffix = f'; plus {remaining} more duplicate group(s)' if remaining > 0 else ''
    raise RuntimeError(
        'Cannot add unique_general_culture_name_per_project because duplicate '
        f'general culture names already exist: {details}{suffix}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0090_project_region'),
    ]

    operations = [
        migrations.RunPython(assert_no_duplicate_general_culture_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='culture',
            constraint=models.UniqueConstraint(
                fields=('project', 'name_normalized'),
                condition=(
                    models.Q(deleted_at__isnull=True)
                    & (models.Q(variety_normalized__isnull=True) | models.Q(variety_normalized=''))
                ),
                name='unique_general_culture_name_per_project',
                violation_error_message='A general culture with this name already exists in this project.',
            ),
        ),
    ]
