# Generated by Claude on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0091_unique_general_culture_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month a season starts on (1-31).')),
                ('start_month', models.PositiveSmallIntegerField(default=1, help_text='Month a season starts on (1-12).')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Season start date.')),
                ('end_date', models.DateField(help_text='Season end date (inclusive).')),
                ('custom_label', models.CharField(blank=True, help_text="Optional user-chosen override for the computed label (set via 'Umbenennen').", max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seasons', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='farm.project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='plantingplan',
            name='season',
            field=models.ForeignKey(blank=True, help_text="Season this planting plan is scheduled in. Nullable only until a project's first season setup runs.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_plans', to='farm.season'),
        ),
        migrations.AddIndex(
            model_name='plantingplan',
            index=models.Index(fields=['project', 'season'], name='farm_planti_project_3ca1fa_idx'),
        ),
        migrations.AddField(
            model_name='seasonpattern',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_pattern', to='farm.project'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('project', 'start_date'), name='unique_season_start_per_project'),
        ),
    ]
