# Generated by Django 5.2.9 on 2026-08-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0092_add_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('season_delete', 'Season deleted'), ('season_undelete', 'Season restored'), ('season_copy_data', 'Season data copied')], max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_operations', to='farm.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='entityrevision',
            name='batch_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='farm.batchoperation'),
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['project', '-created_at'], name='farm_batcho_project_3aa68d_idx'),
        ),
    ]
