# Generated by Django 5.2.9 on 2026-08-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0094_batch_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchoperation',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchoperation',
            name='operation_type',
            field=models.CharField(choices=[('season_create', 'Season created'), ('season_delete', 'Season deleted'), ('season_undelete', 'Season restored'), ('season_copy_data', 'Season data copied'), ('batch_reverted', 'Batch operation reverted')], max_length=40),
        ),
    ]
