"""Point the renamed Crop relations at their new reverse accessors."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0010_sync_dach_crop_species_seed_data"),
        ("farm", "0098_rename_culture_to_crop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="crop_species",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional official crop species link used when publishing to the public library.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_crops",
                to="crops.cropspecies",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="image_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Referenced media file for this crop image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crops",
                to="farm.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="farm.project",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="selected_seed_demand_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Persisted supplier selection for seed-demand package calculations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seed_demand_crops",
                to="farm.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="source_public_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_crops",
                to="farm.publiccrop",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Seed supplier (preferred over seed_supplier text field)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crops",
                to="farm.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="cropimportdraft",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_import_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cropimportdraft",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_import_drafts",
                to="farm.project",
            ),
        ),
        migrations.AlterField(
            model_name="cropsupplierdata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_supplier_data",
                to="farm.project",
            ),
        ),
        migrations.AlterField(
            model_name="cropsupplierdata",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_supplier_data",
                to="farm.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="plantingplan",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional until the plan is fully filled in — a plan can be saved as a draft before a crop is chosen, as long as a bed is chosen instead.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planting_plans",
                to="farm.crop",
            ),
        ),
        migrations.AlterField(
            model_name="publiccrop",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccrop",
            name="crop_species",
            field=models.ForeignKey(
                blank=True,
                help_text="Official crop species required for new public-library publications.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_crops",
                to="crops.cropspecies",
            ),
        ),
        migrations.AlterField(
            model_name="publiccrop",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_crops",
                to="farm.project",
            ),
        ),
        migrations.AlterField(
            model_name="publiccrop",
            name="source_project_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_public_crops",
                to="farm.crop",
            ),
        ),
        migrations.AlterField(
            model_name="publiccrop",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_public_crops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropchangeproposal",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crop_change_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropchangeproposal",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_public_crop_change_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropdiscussioncomment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crop_discussion_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropdiscussioncomment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_public_crop_discussion_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropdiscussiontopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crop_discussion_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccroprevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crop_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publiccropstatusevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_crop_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
