# Generated by Django 5.2.9 on 2026-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0103_link_published_crops_to_owned_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="rejected_public_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 over the public values the declined diff showed. The notice stays silent while the public entry still carries exactly those values, so a version bump that changes nothing the copy compares against (an identical re-publish, a translation-only edit) does not ask the same question again.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="rejected_public_version",
            field=models.IntegerField(
                blank=True,
                help_text="Public-library version the user explicitly declined to take over. Kept for rejections recorded before rejected_public_fingerprint existed; the fingerprint is what silences the notice now.",
                null=True,
            ),
        ),
    ]
