# Generated by Django 5.2.9 on 2026-07-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_seed_initial_crop_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropspecies',
            options={'ordering': ['name'], 'permissions': [('moderate_crop_species', 'Can moderate crop species proposals')], 'verbose_name': 'Crop species', 'verbose_name_plural': 'Crop species'},
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_species_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropspecies',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_crop_species_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cropspecies',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('proposed', 'Proposed'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicLibraryModeratorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_library_moderator_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_library_moderator_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public library moderator request',
                'verbose_name_plural': 'Public library moderator requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_public_library_moderator_request_per_user')],
            },
        ),
    ]
