# Generated by Django 5.2.9 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0003_alter_cropspecies_options_cropspecies_proposed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropSpeciesTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("common_name", models.CharField(max_length=200)),
                (
                    "common_name_normalized",
                    models.CharField(db_index=True, editable=False, max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="crops.cropspecies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop species translation",
                "verbose_name_plural": "Crop species translations",
                "ordering": ["language_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "language_code"),
                        name="unique_crop_species_translation_per_language",
                    )
                ],
            },
        ),
    ]
