# Generated by Codex on 2026-08-20

from django.db import migrations, models


def backfill_search_text(apps, schema_editor):
    from farm.utils import normalize_text

    CropSpeciesTranslation = apps.get_model('crops', 'CropSpeciesTranslation')
    for translation in CropSpeciesTranslation.objects.all().iterator():
        terms = [translation.common_name]
        synonyms = translation.synonyms if isinstance(translation.synonyms, list) else []
        regional_names = translation.regional_names if isinstance(translation.regional_names, dict) else {}
        terms.extend(item for item in synonyms if isinstance(item, str))
        terms.extend(item for item in regional_names.values() if isinstance(item, str))
        normalized_terms = []
        for term in terms:
            normalized = normalize_text(term)
            if normalized:
                normalized_terms.append(normalized)
        translation.search_text_normalized = (
            '\n' + '\n'.join(dict.fromkeys(normalized_terms)) + '\n'
            if normalized_terms
            else ''
        )
        translation.save(update_fields=['search_text_normalized'])


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_sync_expanded_crop_species_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropspeciestranslation',
            name='regional_names',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cropspeciestranslation',
            name='search_text_normalized',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='cropspeciestranslation',
            name='synonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_search_text, migrations.RunPython.noop),
    ]
