# Generated by Codex on 2026-08-20

from django.db import migrations


def build_search_text(common_name, synonyms, regional_names):
    from farm.utils import normalize_text

    terms = [common_name]
    terms.extend(item for item in synonyms if isinstance(item, str))
    terms.extend(item for item in regional_names.values() if isinstance(item, str))
    normalized_terms = []
    for term in terms:
        normalized = normalize_text(term)
        if normalized:
            normalized_terms.append(normalized)
    return (
        '\n' + '\n'.join(dict.fromkeys(normalized_terms)) + '\n'
        if normalized_terms
        else ''
    )


def add_aubergine_regional_alias(apps, schema_editor):
    CropSpeciesTranslation = apps.get_model('crops', 'CropSpeciesTranslation')
    translation = (
        CropSpeciesTranslation.objects
        .filter(
            species__name_normalized='aubergine',
            language_code='de',
        )
        .first()
    )
    if translation is None:
        return

    regional_names = (
        translation.regional_names
        if isinstance(translation.regional_names, dict)
        else {}
    )
    if regional_names.get('austria') == 'Melanzani':
        return

    regional_names = {**regional_names, 'austria': 'Melanzani'}
    synonyms = translation.synonyms if isinstance(translation.synonyms, list) else []
    translation.regional_names = regional_names
    translation.search_text_normalized = build_search_text(
        translation.common_name,
        synonyms,
        regional_names,
    )
    translation.save(update_fields=['regional_names', 'search_text_normalized'])


def remove_aubergine_regional_alias(apps, schema_editor):
    CropSpeciesTranslation = apps.get_model('crops', 'CropSpeciesTranslation')
    translation = (
        CropSpeciesTranslation.objects
        .filter(
            species__name_normalized='aubergine',
            language_code='de',
        )
        .first()
    )
    if translation is None or not isinstance(translation.regional_names, dict):
        return

    regional_names = {
        key: value
        for key, value in translation.regional_names.items()
        if not (key == 'austria' and value == 'Melanzani')
    }
    synonyms = translation.synonyms if isinstance(translation.synonyms, list) else []
    translation.regional_names = regional_names
    translation.search_text_normalized = build_search_text(
        translation.common_name,
        synonyms,
        regional_names,
    )
    translation.save(update_fields=['regional_names', 'search_text_normalized'])


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_crop_species_regional_names'),
    ]

    operations = [
        migrations.RunPython(
            add_aubergine_regional_alias,
            remove_aubergine_regional_alias,
        ),
    ]
