# Generated by Codex on 2026-08-24

from django.db import migrations


def _generic_kohl_species_ids(apps, normalized_kohl):
    CropSpecies = apps.get_model('crops', 'CropSpecies')
    CropSpeciesTranslation = apps.get_model('crops', 'CropSpeciesTranslation')

    generic_species_ids = set(
        CropSpecies.objects
        .filter(name_normalized=normalized_kohl)
        .values_list('id', flat=True)
    )
    generic_species_ids.update(
        CropSpeciesTranslation.objects
        .filter(common_name_normalized=normalized_kohl)
        .values_list('species_id', flat=True)
    )
    return generic_species_ids


def reject_generic_kohl_species(apps, schema_editor):
    """Remove the old generic "Kohl" species from public upload suggestions."""
    from farm.utils import normalize_text

    CropSpecies = apps.get_model('crops', 'CropSpecies')

    normalized_kohl = normalize_text('Kohl') or 'kohl'
    generic_species_ids = _generic_kohl_species_ids(apps, normalized_kohl)
    if not generic_species_ids:
        return

    CropSpecies.objects.filter(id__in=generic_species_ids).update(
        status='rejected',
        review_note=(
            'Automatically rejected: generic "Kohl" is too broad for crop-library '
            'publishing. Use concrete crop species such as Weißkraut, Karfiol, '
            'Chinakohl, Grünkohl, Kohlrabi, Rotkraut or Wirsing.'
        ),
    )


def unreject_generic_kohl_species(apps, schema_editor):
    from farm.utils import normalize_text

    CropSpecies = apps.get_model('crops', 'CropSpecies')
    normalized_kohl = normalize_text('Kohl') or 'kohl'
    generic_species_ids = _generic_kohl_species_ids(apps, normalized_kohl)
    if not generic_species_ids:
        return

    CropSpecies.objects.filter(id__in=generic_species_ids).update(
        status='published',
        review_note='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_add_aubergine_regional_alias'),
    ]

    operations = [
        migrations.RunPython(
            reject_generic_kohl_species,
            unreject_generic_kohl_species,
        ),
    ]
