# Generated by Codex on 2026-08-25

from django.db import migrations


def sync_dach_crop_species_seed_data(apps, schema_editor):
    from crops.seed_data import CROP_SPECIES_SEED_DATA, get_crop_species_seed_name
    from farm.utils import normalize_text

    CropSpecies = apps.get_model('crops', 'CropSpecies')
    CropSpeciesTranslation = apps.get_model('crops', 'CropSpeciesTranslation')

    for entry in CROP_SPECIES_SEED_DATA:
        name = get_crop_species_seed_name(entry, 'de')
        normalized_name = normalize_text(name) or ''
        species = CropSpecies.objects.filter(name_normalized=normalized_name).first()
        if species is None:
            species = CropSpecies.objects.create(
                name=name,
                name_normalized=normalized_name,
                status='published',
            )
        else:
            species.name = name
            species.name_normalized = normalized_name
            species.status = 'published'
            species.save(update_fields=['name', 'name_normalized', 'status'])

        for language_code, common_name in entry.translations.items():
            cleaned_language_code = (language_code or '').strip().lower()
            cleaned_common_name = ' '.join((common_name or '').split())
            CropSpeciesTranslation.objects.update_or_create(
                species=species,
                language_code=cleaned_language_code,
                defaults={
                    'common_name': cleaned_common_name,
                    'common_name_normalized': normalize_text(cleaned_common_name) or '',
                },
            )

    generic_green_manure_names = ['Gründüngung', 'Green manure']
    generic_green_manure_normalized = [
        normalize_text(name) or ''
        for name in generic_green_manure_names
    ]
    generic_species_ids = set(
        CropSpecies.objects
        .filter(name_normalized__in=generic_green_manure_normalized)
        .values_list('id', flat=True)
    )
    generic_species_ids.update(
        CropSpeciesTranslation.objects
        .filter(common_name_normalized__in=generic_green_manure_normalized)
        .values_list('species_id', flat=True)
    )
    if generic_species_ids:
        CropSpecies.objects.filter(id__in=generic_species_ids).update(
            status='rejected',
            review_note=(
                'Automatically rejected: "Gründüngung" / "Green manure" is a use '
                'category, not a crop species. Use concrete species such as '
                'Buchweizen, Phacelia, Inkarnatklee, Ölrettich, Rotklee or '
                'Winterroggen instead.'
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_reject_generic_kohl_species'),
    ]

    operations = [
        migrations.RunPython(
            sync_dach_crop_species_seed_data,
            migrations.RunPython.noop,
        ),
    ]
